### PR TITLE
use no-reply@<customer>.innoactive.io as sender address

### PR DESCRIPTION
**Pull request by klyse**

### CODE REVIEW

**Review by burnedikt — APPROVED** [review]

**Review by burnedikt — CHANGES_REQUESTED** [review]
Tests fail because `base_hostname` is undefined

**Comment by klyse** [comment]
`base_hostname` gets dumped from the terraform output and is stored in the ansible vars file.

**Comment by burnedikt** [comment]
> `base_hostname` gets dumped from the terraform output and is stored in the ansible vars file.

yeah, but this role does not know that that's a required input parameter. If it is, then it also should be added to `defaults.yml`. The idea is that this role can setup a portal instance without making any assumptions about the hostnames, by introducing a `base_hostname`. Our calling code (i.e. ansible playbooks use the `base_hostname` internally to come up with hostnames for portal, backend, customization etc. but this role does not know about it).

Since the e-mail is configurable already (setting `from_email` variable) I guess the easiest way is to just set this in our playbook where we actually know what's the desired value and keep this role here stupid in providing some defaults which can easily be overridden.

If we want to introduce the `base_hostname` here than we'd have to fully do it, i.e. also dynamically create the ohter hostnames like `portal_hostname` etc. based on the `base_hostname`, add it to `defaults.yml` and add documentation for it to the readme.

**Comment by klyse** [comment]
Closing this PR because it can be solved easier: https://github.com/Innoactive/Hub-Backend-Configuration-Management/commit/aed92a097f559904bd1891551c947cd037ddd1b3

**Pull request closed without merging**
